spring:
  datasource:
    url: jdbc:postgresql://localhost:${DATA_HOST}/${DATA_NAME}
    password: ${DATA_PASSWORD}
    username: ${DATA_USERNAME}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml